In [2]:
import numpy as np

In [5]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [6]:
type(a)

numpy.ndarray

In [7]:
print(a+b)
print(a-b)
print(a*b)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


In [9]:
#creating 2d array
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [10]:
#creating a 3d array
a3 = np.array([[[1,2,3],[4,5,6]],
               [[7,8,9],[10,11,12]],
               [[13,14,15],[16,17,18]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [12]:
print(a2.shape)
print(a3.shape)

(2, 3)
(3, 2, 3)


In [13]:
print(a2.ndim)
print(a3.ndim)

2
3


In [14]:
print(a2.dtype)

int64


In [17]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [28]:
np.random.randint(1,11,size = (2,3))

array([[[10,  8,  3],
        [ 5,  3,  2]],

       [[ 3,  2,  9],
        [ 3,  8,  5]],

       [[ 5,  8,  2],
        [ 3,  9, 10]]])

In [29]:
np.random.randint(1,11,size = (3,2,3))

array([[[ 5,  7,  7],
        [ 4,  1,  9]],

       [[ 5, 10,  3],
        [ 8, 10, 10]],

       [[ 8,  8,  3],
        [ 2,  7,  6]]])

In [32]:
x = np.random.randint(1,21,size = (2,2))
y = np.random.randint(1,21,size = (2,2))
print(x)
print(y)

[[ 7 16]
 [17 13]]
[[ 3 17]
 [ 9  9]]


In [33]:
print(x+y)
print(x-y)
print(x*y)

[[10 33]
 [26 22]]
[[ 4 -1]
 [ 8  4]]
[[ 21 272]
 [153 117]]


In [35]:
#matrix multiplication
#1st method
print(x @ y)  

[[165 263]
 [168 406]]


In [36]:
#2nd method
np.dot(x,y)

array([[165, 263],
       [168, 406]])

In [39]:
# Multiplies all elements in an array
print(x.prod())
print(y.prod())

24752
4131


In [42]:
print(x.mean())
print(y.mean())

13.25
9.5


In [46]:
print(x)

[[ 7 16]
 [17 13]]


In [43]:
b = x.mean(axis = 0) #column wise - calculates mean
print(b)

[12.  14.5]


In [45]:
c = x.mean(axis = 1) #row wise - calculates mean
print(c)

[11.5 15. ]


In [49]:
print(x.sum())
print(x.std()) #standard deviation
print(x.var()) #standard variance

53
3.897114317029974
15.1875


In [62]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(arr, 50))
print(np.percentile(arr, 25))
print(np.percentile(arr, 75))
print(np.percentile(arr, 90))

5.0
3.0
7.0
8.2


In [63]:
arr2 = np.random.randint(11,100,(4,4))
print(arr2)

[[37 79 79 48]
 [73 32 29 50]
 [24 56 44 63]
 [97 30 74 54]]


In [66]:
print('2x8')
print(arr2.reshape(2,8))
print('8x2')
print(arr2.reshape(8,2))

2x8
[[37 79 79 48 73 32 29 50]
 [24 56 44 63 97 30 74 54]]
8x2
[[37 79]
 [79 48]
 [73 32]
 [29 50]
 [24 56]
 [44 63]
 [97 30]
 [74 54]]
